### ISSUE TITLE
Team name should not be empty

### ISSUE THREAD

**Issue by hornofj** [Einstore/Einstore#102]
it is possible to add a team with empty name

- [ ] handle on API
- [ ] handle on frontend

![Bildschirmfoto 2019-05-20 um 10 20 44](https://user-images.githubusercontent.com/2500352/58006720-0157a300-7ae9-11e9-98b4-b298c82a4462.png)

**Comment by rafiki270** [comment]
defo a server issue, this should never happen ... although it has to be handled on the frontend too
