### ISSUE TITLE
Fix migrations: Relation Setting does not exist

### ISSUE THREAD

**Issue by ViliamKopecky** [Einstore/Einstore#134]
![Screenshot 2019-06-10 at 18 04 45](https://user-images.githubusercontent.com/316435/60262418-679cc600-98de-11e9-91d0-8d71b101c017.png)

uninstall+install doesnt help.

Your note:

> jo pockej, ja daval settings primo do apicore … tak mozna ze to jen nezavadim …

**Comment by ViliamKopecky** [comment]
@rafiki270 Solved?

**Comment by rafiki270** [comment]
yes :)
