### ISSUE TITLE
Receive error when upload apk by api

### ISSUE THREAD

**Issue by thanhpd-teko** [Einstore/Einstore#150]
Hi, i received below error when upload apk by api key:
```
{
    "description": "You shall not pass!",
    "error": "httperror.not_authorized"
}
```
```
curl --location --request POST 'https://api_url.com/builds?token=api_key' \
--header 'Content-Type: application/vnd.android.package-archive' \
--data-binary '@/C:/Desktop/app-dev.apk'
```

When generated new api key and upload again it success? However when server restarted then the error occured. Please help me. Thanks

**Comment by thanhpd-teko** [comment]
@rafiki270  please help me.

**Comment by kuhahahaha** [comment]
I encountered the same problem.It sometimes appears，not always.

**Comment by mthuong** [comment]
@thanhpd-teko Have you call to correct port of API server?
