### ISSUE TITLE
cannot login after run

### ISSUE THREAD

**Issue by yangboyd** [Einstore/Einstore#153]
cannot login after run

**Comment by rafiki270** [comment]
Have you ran the install endpoint?

**Comment by rafiki270** [comment]
To create the database structure

**Comment by yangboyd** [comment]
Followed the guid:

Basic usage
To install run make install-db
To start and stop the project make up and make stop
Run make help or just make for other commands
Optionally look into the Makefile for all remaining scripts
Login
Default username and password is core@liveui.io/sup3rS3cr3t

I can see the login page, but cannot login.
Another question: how to set the email part, so it can send password reset email?
