### ISSUE TITLE
Custom S3 Configuration

### ISSUE THREAD

**Issue by davegreco** [Einstore/Einstore#155]
Hi, the plugin from LiveUI S3 that is being used supports custom configuation for minio, do spaces, etc... But currently only a region is configurable. Can we get this expanded to support custom s3 buckets? Also is there any migration from local storage to S3? or back again?

**Comment by rafiki270** [comment]
Hi @davegreco, unfortunately there is no migration as we, in our context where we mainly distribute test builds, deemed any binaries "disposable". The Einstore should support all options of LiveUI S3 module, could you please point me to a specific problem?

**Comment by davegreco** [comment]
Thanks for the quick reply.

So there is only an option for a region and the example for using a custom url on your other repo requires you to use the region east and to construct a different configuration that includes the host. How can this be achieved through the einstorecore configuration? I'm probably just missing it and it's not covered in the main documentation. I would really prefer to use spaces or minio to S3 though.

**Comment by rafiki270** [comment]
I see, sounds like we would have to make some modifications there. All our infrastructure is on AWS atm unfortunately

**Comment by davegreco** [comment]
Most of mine is as well, but we’re trying digital ocean out with this and we use Minio for development stacks. I don’t want to deal with the headache of switching this from local storage to S3 so I think I will just setup an S3 bucket for now. Hopefully this is something supported in the future, I wish that I had some extra time to implement and contribute it back.
