### ISSUE TITLE
CORS configuration

### ISSUE THREAD

**Issue by davegreco** [Einstore/Einstore#156]
I got this up and running on my custom dns with docker on a private server but once I added SSL which is good in general and required for IPA files I started getting CORS preflight check errors in my browsers. I sorted through the code and there doesn't seem to be any method of exposing allowed origins through configuration furthermore the server doesn't appear to be adding any headers for this so it appears as if it is a browser default or maybe it's some default header added by react. Has anyone encountered this and if so how did you go about fixing it?

**Comment by rafiki270** [comment]
Are you using the backend admin panel provided? We have these working without an issue together :/ … the CORS support is through Vapor middleware I believe which is the underlaying swift framework.

**Comment by davegreco** [comment]
Yes, I am using this in a kubernetes cluster running pods of an image built off of a fork of EinstoreAdmin.git and EinstoreCore.git

To give you context on the forking I couldn't get the container to pick up REACT_APP_API_URL unless I adjusted the dockerfile format so that it would pick that up from my containers env variables so I changed ENV REACT_APP_API_URL '%REACT_APP_API_URL%' to ENV REACT_APP_API_URL "$REACT_APP_API_URL"

It was working fine when this was running on http but it started failing when I switched it to https which I don't understand why. Is vapor only adding CORS once it detects the scheme is https?

The site is being served from
appstore.heizenrader.com

The api is being served from
api.appstore.heizenrader.com

A second set of eyes to see if anything stands out would be super helpful. I understand CORS as we use it heavily in our own projects but there just doesn't appear to be any configuration exposed and even looking through the core code I don't see that it is intentionally adding any CORS configurations (maybe I am missing it though) it makes sense that it would have a CORS issue since they are running on different dns which from the documentation sounded like it was the expected way for it to run (with the combined endpoint ie "/api" on the uri instead of the subdomain being an optional thing, which I would prefer not to setup to get it working)

**Comment by davegreco** [comment]
I tried doing this in my fork https://docs.vapor.codes/2.0/http/cors/
putting the files into EinstoreCore/Sources/EinstoreCore/Config but it doesn't appear to be picked up at all, I'm not even certain that it is the correct place to put it.

**Comment by rafiki270** [comment]
@davegreco could you let me know what was the issue please?

**Comment by davegreco** [comment]
I wish that I knew, since I can't figure it out I'm going to likely just host these things on dropbox. It isn't ideal but we don't have a budget to pay for a hosted solution and I just don't know how to fix this. I deleted the previous messages since they just contained slightly personal information about our usage of it which didn't seem great to leave around, I planned to remove them regardless of figuring it out.
