### ISSUE TITLE
Back to Dashboard after delete build

### ISSUE THREAD

**Issue by lszedeli** [Einstore/Einstore#51]
- [x] after "delete this build" and "delete all builds" users should return to the dashboard
- [x] delete app does not seem to work despite "delete all builds" (still present on dashboard)

**Comment by rafiki270** [comment]
@ViliamKopecky do you have an idea if this is backend or frontend please?

**Comment by ViliamKopecky** [comment]
@rafiki270 frontend :)

**Comment by ViliamKopecky** [comment]
Frontend part of this should be done. But there is still issue that cluster is still existing with empty builds and the number of builds are weird.
