### ISSUE TITLE
Some cards have loaded with no content?

### ISSUE THREAD

**Issue by rafiki270** [Einstore/Einstore#60]
<img width="1681" alt="image" src="https://user-images.githubusercontent.com/218245/56771934-1a9e5580-67b0-11e9-82b4-368871042e83.png">

**Comment by ViliamKopecky** [comment]
Are you sure this is a frontend issue?

**Comment by rafiki270** [comment]
Only seen it twice and different places so would assume so, not 100% tho

**Comment by rafiki270** [comment]
nope, my problem :D

**Comment by ViliamKopecky** [comment]
So... close this? :D
