### ISSUE TITLE
Server logo upload on `/system` doesn't work

### ISSUE THREAD

**Issue by rafiki270** [Einstore/Einstore#63]
doesn't seem to trigger the actual upload

**Comment by ViliamKopecky** [comment]
Works for me… dont forget it must be a square of some size :)

**Comment by rafiki270** [comment]
nope, not for me on any browser :( ... only through postman

**Comment by ViliamKopecky** [comment]
Still? I cannot reproduce :(

**Comment by rafiki270** [comment]
Yes, tap on a logo, select image and tap save image. Old one is still present

**Comment by rafiki270** [comment]
Upload works, other issues in separate tickets
