### ISSUE TITLE
Search by multiple tags

### ISSUE THREAD

**Issue by ViliamKopecky** [Einstore/Einstore#85]
- info: tags delimiter in search is `|` - previously thought it should be json serialized array.
- <del>if one build has two tags, and both tags are in search - the same build shows twice. And provided `id` is not `build.id` but `build_tag.id` - so links dont work - reason of #74</del>

**Comment by rafiki270** [comment]
it is not search but filter, so more tags, less apps ... what we need is "what is left system" where API only returns tags that are still available and shows in what number. This will be though difficult without a service like ElasticCloud as we primarily have to support self hosted solution

**Comment by ViliamKopecky** [comment]
Read it once more, i really think the filter is wrong 😀 and the idea is a separate issue.

**Comment by ViliamKopecky** [comment]
### this build has two tags:

<img width="431" alt="Screenshot 2019-05-15 at 09 42 51" src="https://user-images.githubusercontent.com/316435/57757644-2ff30980-76f6-11e9-9b4d-6c8f85690d6e.png">

---

### search by one of these tags returns correctly this build:

<img width="1256" alt="Screenshot 2019-05-15 at 09 43 02" src="https://user-images.githubusercontent.com/316435/57757655-37b2ae00-76f6-11e9-8dcf-29c6c8c4ab2e.png">

---

### but search by those two tags returns the same build twice - wrong and also contradictory to your "more tags, less apps":

<img width="1237" alt="Screenshot 2019-05-15 at 09 43 12" src="https://user-images.githubusercontent.com/316435/57757662-3aad9e80-76f6-11e9-8259-13d0edba5033.png">

**Comment by rafiki270** [comment]
fixed in https://github.com/Einstore/EinstoreCore/pull/63
