### ISSUE TITLE
Add new team - prefill identifier

### ISSUE THREAD

**Issue by hornofj** [Einstore/Einstore#98]
team name and "Team Identifier" ("team-identifier")

team identifier should be generated from the team name but the user can override the suggested indentifier, the app needs to check if the identifier is unique

the identifier should be prefilled onkeyup or on onblur when filling the team name in, now the identifier is not visible

**Comment by rafiki270** [comment]
There is an endpoint to check if team identifier is available

**Comment by rafiki270** [comment]
There is an endpoint to check if identifier is available before we send the main request
